### ISSUE TITLE
Watch for views

### ISSUE THREAD

**Issue by sdogruyol** [jwoertink/guard-kemal#2]
This is the clone for https://github.com/jwoertink/fez/issues/10

**Comment by jwoertink** [comment]
I fixed a few bugs with how things were loading. I decided not to add anything extra for views. Instead, you can do this

``` ruby
guard 'kemal', path: 'src', file: 'server.cr' do
  watch('src/server.cr') # watch the main kemal server
  watch(%r{src/.*\.ecr}) # watch your views
end
```

It's pretty clean, and allows for more customization. I've also added this in to fez by default.
